global: 
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

receivers:
- name: telegram_critical
  telegram_configs:
    - chat_id: -1
      bot_token: "1"
      api_url: "https://api.telegram.org"
      send_resolved: true
- name: telegram_warning
  telegram_configs:
    - chat_id: -1
      bot_token: "1"
      api_url: "https://api.telegram.org"
      send_resolved: true
  
route:
  group_by: ['instance']
  receiver: telegram_critical
  routes:
  - receiver: telegram_critical
    continue: true
    matchers:
      - severity="critical"

  - receiver: telegram_warning
    continue: true
    matchers:
      - severity="warning"
    active_time_intervals:
      - worktime


time_intervals:
- name: worktime
  time_intervals:
  - weekdays: ['monday:friday']
    times:
    - start_time: 09:00
      end_time: 18:00

