version: '3.7'

volumes:
    prometheus_data: {}
    vmdata: {}
    service_discovery: {}
    alertmanager_data: {}
networks:
  iris:

services:

  roomkn-nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/certs/
    networks:
      - iris
    labels:
      co.elastic.logs/enabled: "true" 

  roomkn-grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - iris

  roomkn-prometheus:
    image: prom/prometheus:v2.36.2
    environment:
      - ROOMKN_WEB_HOST=${ROOMKN_WEB_HOST}
      - ROOMKN_WEB_PORT=${ROOMKN_WEB_PORT}
      - ROOMKN_API_HOST=${ROOMKN_API_HOST}
      - ROOMKN_API_PORT=${ROOMKN_API_PORT}

      - NODE_EXPORTER_HOST=${NODE_EXPORTER_HOST}
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - iris
    restart: always
    labels:
      prometheus-job: "prometheus"

  # roomkn-alertmanager:
  #   image: quay.io/prometheus/alertmanager
  #   volumes:
  #     - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #     - alertmanager_data:/alertmanager/data
  #   command: 
  #     - '--config.file=/etc/alertmanager/alertmanager.yml'
  #   ports:
  #     - 9093:9093
  #   networks:
  #     - iris

  roomkn-blackbox:
    image: prom/blackbox-exporter
    ports:
    - 9115:9115
    command:
    - --config.file=/etc/blackbox/blackbox.yml
    volumes:
    - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    networks:
    - iris

