global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
# remote_write:
#   - url: http://victoriametrics:8428/api/v1/write
#     queue_config:
#       max_samples_per_send: 10000
#       capacity: 20000
#       max_shards: 30
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: "node_exporter"
    scrape_interval: 10s
    static_configs:
          - targets: ['109.120.182.138:9100']  
  - job_name: 'blackbox_exporter_http'
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [http_probe]
    static_configs:
    - targets:
        - 109.120.182.138:80
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: roomkn-blackbox:9115